version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=1234567890!@>$%
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: Yonatan
      POSTGRES_PASSWORD: yonatan123
      POSTGRES_DB: payroll_info
    ports:
      - "5432:5432"
